version: '3.8'

services:
  coffeeshop.products.api:
    build:
      context: .
      dockerfile: CoffeeShop.Products.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ProductsConnection=Server=tcp:coffee-shop.database.windows.net,1433;Initial Catalog=CoffeeShop_Products;User ID=;Password=
      