// <auto-generated />
using System;
using CoffeeShop.Products.Api.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShop.Products.Api.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShop.Products.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "FoodItems"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Others"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "WholeBean",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ground",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Instant",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pods",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Specialty",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CoffeeMakers",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grinders",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mugs",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Filters",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pastries",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Snacks",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Syrups",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MilkAlternatives",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Merchandise",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Subscriptions",
                            ParentCategoryId = 4
                        });
                });

            modelBuilder.Entity("CoffeeShop.Products.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5840),
                            Name = "WholeBean_Product_1",
                            Price = 81.6067333484314m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5893)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5904),
                            Name = "WholeBean_Product_2",
                            Price = 45.1314224486633m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5907)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5912),
                            Name = "WholeBean_Product_3",
                            Price = 10.6145763725502m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5915)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5921),
                            Name = "WholeBean_Product_4",
                            Price = 98.2392922583436m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5923)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5929),
                            Name = "WholeBean_Product_5",
                            Price = 88.2227239652338m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5931)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5938),
                            Name = "WholeBean_Product_6",
                            Price = 49.4043652849489m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5941)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5946),
                            Name = "WholeBean_Product_7",
                            Price = 41.9169384436571m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5949)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5955),
                            Name = "WholeBean_Product_8",
                            Price = 61.107232387303m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5957)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5963),
                            Name = "Ground_Product_9",
                            Price = 58.8177451961799m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5965)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5974),
                            Name = "Ground_Product_10",
                            Price = 81.5861204760637m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5977)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5983),
                            Name = "Ground_Product_11",
                            Price = 64.6856602191068m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5985)
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5990),
                            Name = "Ground_Product_12",
                            Price = 85.4344787472334m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5993)
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(5998),
                            Name = "Ground_Product_13",
                            Price = 60.817610446475m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6001)
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6006),
                            Name = "Ground_Product_14",
                            Price = 22.6052073293656m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6009)
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6014),
                            Name = "Ground_Product_15",
                            Price = 78.0221387851453m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6017)
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6022),
                            Name = "Ground_Product_16",
                            Price = 87.6589588728787m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6024)
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6030),
                            Name = "Ground_Product_17",
                            Price = 59.6695983795678m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6032)
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6039),
                            Name = "Instant_Product_18",
                            Price = 18.7204377179728m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6042)
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6047),
                            Name = "Instant_Product_19",
                            Price = 32.5601733546598m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6050)
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6055),
                            Name = "Instant_Product_20",
                            Price = 56.5176904794962m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6058)
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6063),
                            Name = "Instant_Product_21",
                            Price = 10.2473023266033m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6065)
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6071),
                            Name = "Instant_Product_22",
                            Price = 70.5546851472502m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6073)
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6078),
                            Name = "Instant_Product_23",
                            Price = 86.1797021032742m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6081)
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6086),
                            Name = "Instant_Product_24",
                            Price = 12.0237213308709m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6089)
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6094),
                            Name = "Instant_Product_25",
                            Price = 52.2621937209356m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6097)
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6102),
                            Name = "Pods_Product_26",
                            Price = 81.3474761981931m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6104)
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6110),
                            Name = "Pods_Product_27",
                            Price = 92.1703729189075m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6112)
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6117),
                            Name = "Pods_Product_28",
                            Price = 73.9866027309082m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6119)
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6125),
                            Name = "Pods_Product_29",
                            Price = 96.2389276842317m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6127)
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6133),
                            Name = "Pods_Product_30",
                            Price = 30.157653900386m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6135)
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6140),
                            Name = "Pods_Product_31",
                            Price = 32.1417895615493m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6143)
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6148),
                            Name = "Pods_Product_32",
                            Price = 39.0398640281992m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6151)
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6156),
                            Name = "Pods_Product_33",
                            Price = 25.1183859464384m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6158)
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6165),
                            Name = "Pods_Product_34",
                            Price = 61.9970556973045m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6168)
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6173),
                            Name = "Specialty_Product_35",
                            Price = 1.73436805430758m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6176)
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6182),
                            Name = "Specialty_Product_36",
                            Price = 68.7269975617305m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6184)
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6190),
                            Name = "Specialty_Product_37",
                            Price = 77.5090844613122m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6192)
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6198),
                            Name = "Specialty_Product_38",
                            Price = 16.1257409961252m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6200)
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6205),
                            Name = "Specialty_Product_39",
                            Price = 37.0374057055212m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6208)
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6213),
                            Name = "Specialty_Product_40",
                            Price = 32.2092272069999m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6215)
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6221),
                            Name = "Specialty_Product_41",
                            Price = 20.2905761369988m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6223)
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6229),
                            Name = "CoffeeMakers_Product_42",
                            Price = 10.4281346441457m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6231)
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6237),
                            Name = "CoffeeMakers_Product_43",
                            Price = 70.7425247197932m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6239)
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6245),
                            Name = "CoffeeMakers_Product_44",
                            Price = 73.5315587427293m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6247)
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6252),
                            Name = "CoffeeMakers_Product_45",
                            Price = 88.0380119388771m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6255)
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6260),
                            Name = "CoffeeMakers_Product_46",
                            Price = 56.2478960826131m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6262)
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6268),
                            Name = "CoffeeMakers_Product_47",
                            Price = 86.734093930808m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6270)
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6276),
                            Name = "CoffeeMakers_Product_48",
                            Price = 24.3143281385188m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6278)
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6320),
                            Name = "CoffeeMakers_Product_49",
                            Price = 87.6152766834918m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6322)
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6328),
                            Name = "Grinders_Product_50",
                            Price = 13.073577632694m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6331)
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6336),
                            Name = "Grinders_Product_51",
                            Price = 78.7955038175101m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6339)
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6344),
                            Name = "Grinders_Product_52",
                            Price = 17.026252989094m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6347)
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6352),
                            Name = "Grinders_Product_53",
                            Price = 51.2892285862515m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6354)
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6360),
                            Name = "Grinders_Product_54",
                            Price = 45.5301787791826m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6362)
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6367),
                            Name = "Grinders_Product_55",
                            Price = 28.5035681572001m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6370)
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6375),
                            Name = "Grinders_Product_56",
                            Price = 74.0515734355406m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6378)
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6383),
                            Name = "Grinders_Product_57",
                            Price = 38.600952790862m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6386)
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6391),
                            Name = "Grinders_Product_58",
                            Price = 8.37704035626912m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6394)
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6399),
                            Name = "Grinders_Product_59",
                            Price = 30.279133200143m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6402)
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6407),
                            Name = "Mugs_Product_60",
                            Price = 17.539989478398m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6410)
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6415),
                            Name = "Mugs_Product_61",
                            Price = 16.9185074085059m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6418)
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6423),
                            Name = "Mugs_Product_62",
                            Price = 15.372347621284m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6425)
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6431),
                            Name = "Mugs_Product_63",
                            Price = 87.8197292730764m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6433)
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6438),
                            Name = "Mugs_Product_64",
                            Price = 85.4631128012597m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6441)
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6446),
                            Name = "Mugs_Product_65",
                            Price = 11.585713236114m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6449)
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6456),
                            Name = "Mugs_Product_66",
                            Price = 61.8582475644492m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6459)
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6464),
                            Name = "Mugs_Product_67",
                            Price = 59.6651809410901m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6466)
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6472),
                            Name = "Mugs_Product_68",
                            Price = 58.6693202716045m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6474)
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6480),
                            Name = "Mugs_Product_69",
                            Price = 41.6498365560763m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6482)
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6488),
                            Name = "Filters_Product_70",
                            Price = 96.3351858751315m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6490)
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6495),
                            Name = "Filters_Product_71",
                            Price = 39.9011259876373m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6498)
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6503),
                            Name = "Filters_Product_72",
                            Price = 88.4498689875424m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6506)
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6511),
                            Name = "Filters_Product_73",
                            Price = 5.48606881162508m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6514)
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6519),
                            Name = "Filters_Product_74",
                            Price = 19.2441254685083m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6521)
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6527),
                            Name = "Filters_Product_75",
                            Price = 10.8593087967208m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6529)
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6535),
                            Name = "Filters_Product_76",
                            Price = 71.069521940502m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6537)
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6543),
                            Name = "Filters_Product_77",
                            Price = 4.45473693133672m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6545)
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6550),
                            Name = "Filters_Product_78",
                            Price = 93.6444864677507m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6553)
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6558),
                            Name = "Filters_Product_79",
                            Price = 42.4257307997533m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6561)
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6566),
                            Name = "Pastries_Product_80",
                            Price = 7.08284968456827m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6569)
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6574),
                            Name = "Pastries_Product_81",
                            Price = 88.6536406788253m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6576)
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6582),
                            Name = "Pastries_Product_82",
                            Price = 30.4256851962955m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6585)
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6590),
                            Name = "Pastries_Product_83",
                            Price = 14.4061722285589m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6592)
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6598),
                            Name = "Pastries_Product_84",
                            Price = 23.0464309029277m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6600)
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6606),
                            Name = "Pastries_Product_85",
                            Price = 75.6546613901226m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6608)
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6613),
                            Name = "Pastries_Product_86",
                            Price = 79.7888194200414m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6616)
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6621),
                            Name = "Pastries_Product_87",
                            Price = 42.2257699562835m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6624)
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6629),
                            Name = "Pastries_Product_88",
                            Price = 47.0571372660194m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6631)
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6636),
                            Name = "Pastries_Product_89",
                            Price = 86.5710737421892m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6639)
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6643),
                            Name = "Snacks_Product_90",
                            Price = 14.5590265036287m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6646)
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6650),
                            Name = "Snacks_Product_91",
                            Price = 32.0677201108052m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6652)
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6657),
                            Name = "Snacks_Product_92",
                            Price = 39.7958009090183m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6659)
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6664),
                            Name = "Snacks_Product_93",
                            Price = 40.5697078155407m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6666)
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6670),
                            Name = "Snacks_Product_94",
                            Price = 14.9476745805661m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6672)
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6677),
                            Name = "Snacks_Product_95",
                            Price = 60.1485354276361m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6680)
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6685),
                            Name = "Snacks_Product_96",
                            Price = 83.2901932772973m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6687)
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6722),
                            Name = "Snacks_Product_97",
                            Price = 47.2676652418351m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6724)
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6730),
                            Name = "Snacks_Product_98",
                            Price = 96.1850965794082m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6732)
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6738),
                            Name = "Snacks_Product_99",
                            Price = 7.6550571779209m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6741)
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6746),
                            Name = "Syrups_Product_100",
                            Price = 53.1416840551104m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6748)
                        },
                        new
                        {
                            Id = 101,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6753),
                            Name = "Syrups_Product_101",
                            Price = 72.6596884651607m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6756)
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6760),
                            Name = "Syrups_Product_102",
                            Price = 53.3726379636248m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6763)
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6768),
                            Name = "Syrups_Product_103",
                            Price = 83.0273076876185m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6770)
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6775),
                            Name = "Syrups_Product_104",
                            Price = 81.739835173706m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6777)
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6782),
                            Name = "Syrups_Product_105",
                            Price = 2.81876414883974m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6784)
                        },
                        new
                        {
                            Id = 106,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6789),
                            Name = "Syrups_Product_106",
                            Price = 13.5958386562073m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6792)
                        },
                        new
                        {
                            Id = 107,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6797),
                            Name = "Syrups_Product_107",
                            Price = 46.2636243991428m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6799)
                        },
                        new
                        {
                            Id = 108,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6804),
                            Name = "Syrups_Product_108",
                            Price = 27.1332038693933m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6807)
                        },
                        new
                        {
                            Id = 109,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6812),
                            Name = "Syrups_Product_109",
                            Price = 60.8475504500594m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6814)
                        },
                        new
                        {
                            Id = 110,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6820),
                            Name = "MilkAlternatives_Product_110",
                            Price = 81.2768480193317m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6822)
                        },
                        new
                        {
                            Id = 111,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6828),
                            Name = "MilkAlternatives_Product_111",
                            Price = 15.1093387935069m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6830)
                        },
                        new
                        {
                            Id = 112,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6835),
                            Name = "MilkAlternatives_Product_112",
                            Price = 73.6882202009531m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6837)
                        },
                        new
                        {
                            Id = 113,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6842),
                            Name = "MilkAlternatives_Product_113",
                            Price = 30.7499155305255m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6844)
                        },
                        new
                        {
                            Id = 114,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6849),
                            Name = "MilkAlternatives_Product_114",
                            Price = 31.1161288748902m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6851)
                        },
                        new
                        {
                            Id = 115,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6856),
                            Name = "MilkAlternatives_Product_115",
                            Price = 93.3740649764787m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6858)
                        },
                        new
                        {
                            Id = 116,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6863),
                            Name = "MilkAlternatives_Product_116",
                            Price = 91.3777150301613m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6866)
                        },
                        new
                        {
                            Id = 117,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6871),
                            Name = "MilkAlternatives_Product_117",
                            Price = 36.5930401815748m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6873)
                        },
                        new
                        {
                            Id = 118,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6878),
                            Name = "Merchandise_Product_118",
                            Price = 86.0904729002193m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6880)
                        },
                        new
                        {
                            Id = 119,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6886),
                            Name = "Merchandise_Product_119",
                            Price = 10.5930336292517m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6888)
                        },
                        new
                        {
                            Id = 120,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6895),
                            Name = "Merchandise_Product_120",
                            Price = 38.6390445223981m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6897)
                        },
                        new
                        {
                            Id = 121,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6902),
                            Name = "Merchandise_Product_121",
                            Price = 91.7443889761065m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6904)
                        },
                        new
                        {
                            Id = 122,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6909),
                            Name = "Merchandise_Product_122",
                            Price = 17.8338283628759m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6911)
                        },
                        new
                        {
                            Id = 123,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6916),
                            Name = "Merchandise_Product_123",
                            Price = 99.3317844047726m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6918)
                        },
                        new
                        {
                            Id = 124,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6923),
                            Name = "Merchandise_Product_124",
                            Price = 63.0370180072504m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6926)
                        },
                        new
                        {
                            Id = 125,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6931),
                            Name = "Merchandise_Product_125",
                            Price = 80.2406407842932m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6933)
                        },
                        new
                        {
                            Id = 126,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6938),
                            Name = "Merchandise_Product_126",
                            Price = 7.6433179483614m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6941)
                        },
                        new
                        {
                            Id = 127,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6946),
                            Name = "Merchandise_Product_127",
                            Price = 62.2676823343731m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6948)
                        },
                        new
                        {
                            Id = 128,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6953),
                            Name = "Subscriptions_Product_128",
                            Price = 0.897609781596431m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6955)
                        },
                        new
                        {
                            Id = 129,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6960),
                            Name = "Subscriptions_Product_129",
                            Price = 55.4653987240797m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6962)
                        },
                        new
                        {
                            Id = 130,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6969),
                            Name = "Subscriptions_Product_130",
                            Price = 96.5956200887607m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6971)
                        },
                        new
                        {
                            Id = 131,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6977),
                            Name = "Subscriptions_Product_131",
                            Price = 57.289829259453m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6980)
                        },
                        new
                        {
                            Id = 132,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6985),
                            Name = "Subscriptions_Product_132",
                            Price = 93.7539763582518m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6987)
                        },
                        new
                        {
                            Id = 133,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6992),
                            Name = "Subscriptions_Product_133",
                            Price = 83.4179562764324m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6994)
                        },
                        new
                        {
                            Id = 134,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(6999),
                            Name = "Subscriptions_Product_134",
                            Price = 63.6949976693159m,
                            UpdatedAt = new DateTime(2024, 7, 10, 19, 14, 59, 388, DateTimeKind.Local).AddTicks(7001)
                        });
                });

            modelBuilder.Entity("CoffeeShop.Products.Api.Models.Category", b =>
                {
                    b.HasOne("CoffeeShop.Products.Api.Models.Category", "ParentCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("CoffeeShop.Products.Api.Models.Product", b =>
                {
                    b.HasOne("CoffeeShop.Products.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoffeeShop.Products.Api.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
