// <auto-generated />
using System;
using CoffeeShop.Products.Api.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShop.Products.Api.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShop.Products.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "FoodItems"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Others"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "WholeBean",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ground",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Instant",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pods",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Specialty",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CoffeeMakers",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grinders",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mugs",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Filters",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pastries",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Snacks",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Syrups",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MilkAlternatives",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Merchandise",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Subscriptions",
                            ParentCategoryId = 4
                        });
                });

            modelBuilder.Entity("CoffeeShop.Products.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6525),
                            Name = "WholeBean_Product_1",
                            Price = 85.6075758591491m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6592)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6609),
                            Name = "WholeBean_Product_2",
                            Price = 28.2907567223371m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6613)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6622),
                            Name = "WholeBean_Product_3",
                            Price = 20.9744044792183m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6626)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6634),
                            Name = "WholeBean_Product_4",
                            Price = 63.3736996522108m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6638)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6646),
                            Name = "WholeBean_Product_5",
                            Price = 13.4279297544984m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6650)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6661),
                            Name = "WholeBean_Product_6",
                            Price = 78.5552142109849m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6665)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6673),
                            Name = "WholeBean_Product_7",
                            Price = 59.2770685572971m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6677)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6687),
                            Name = "Ground_Product_8",
                            Price = 1.5609820809328m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6690)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6699),
                            Name = "Ground_Product_9",
                            Price = 46.199528812862m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6703)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6716),
                            Name = "Ground_Product_10",
                            Price = 15.1380326616443m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6719)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6728),
                            Name = "Ground_Product_11",
                            Price = 37.2237921965464m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6732)
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6740),
                            Name = "Ground_Product_12",
                            Price = 97.1920774243794m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6744)
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6752),
                            Name = "Ground_Product_13",
                            Price = 1.35792072450455m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6756)
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6764),
                            Name = "Ground_Product_14",
                            Price = 20.2653402194981m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6767)
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6775),
                            Name = "Ground_Product_15",
                            Price = 58.1959379706093m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6779)
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6787),
                            Name = "Instant_Product_16",
                            Price = 86.038783843338m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6791)
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6799),
                            Name = "Instant_Product_17",
                            Price = 1.726234337222m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6803)
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6814),
                            Name = "Instant_Product_18",
                            Price = 90.5054342786104m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6818)
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6827),
                            Name = "Instant_Product_19",
                            Price = 83.3277169583034m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6831)
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6839),
                            Name = "Instant_Product_20",
                            Price = 65.6900096248406m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6843)
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6851),
                            Name = "Instant_Product_21",
                            Price = 15.2951137309292m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6855)
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6863),
                            Name = "Instant_Product_22",
                            Price = 11.6781454224071m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6866)
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6874),
                            Name = "Instant_Product_23",
                            Price = 15.7468984871992m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6878)
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6886),
                            Name = "Instant_Product_24",
                            Price = 89.2213592498892m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6890)
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6898),
                            Name = "Pods_Product_25",
                            Price = 19.4631051963757m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6902)
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6909),
                            Name = "Pods_Product_26",
                            Price = 3.36373337338941m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6913)
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6921),
                            Name = "Pods_Product_27",
                            Price = 56.0011706751356m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6925)
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6932),
                            Name = "Pods_Product_28",
                            Price = 26.1559361410841m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6936)
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6944),
                            Name = "Pods_Product_29",
                            Price = 57.6485058521143m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6947)
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6956),
                            Name = "Specialty_Product_30",
                            Price = 56.6043884265326m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6960)
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6968),
                            Name = "Specialty_Product_31",
                            Price = 79.8832222328689m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6972)
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6980),
                            Name = "Specialty_Product_32",
                            Price = 31.4333145486446m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6984)
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6992),
                            Name = "Specialty_Product_33",
                            Price = 11.0694536702073m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(6996)
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7006),
                            Name = "Specialty_Product_34",
                            Price = 14.7326430288659m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7010)
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7018),
                            Name = "Specialty_Product_35",
                            Price = 11.490028357617m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7022)
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7030),
                            Name = "Specialty_Product_36",
                            Price = 62.0371333397594m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7034)
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7091),
                            Name = "Specialty_Product_37",
                            Price = 46.1404016156078m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7095)
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7104),
                            Name = "Specialty_Product_38",
                            Price = 22.5691127883755m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7108)
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7115),
                            Name = "Specialty_Product_39",
                            Price = 35.0280179780895m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7119)
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7128),
                            Name = "CoffeeMakers_Product_40",
                            Price = 85.6970536770584m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7131)
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7140),
                            Name = "CoffeeMakers_Product_41",
                            Price = 81.092970133816m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7143)
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7151),
                            Name = "CoffeeMakers_Product_42",
                            Price = 68.5567015421524m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7155)
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7163),
                            Name = "CoffeeMakers_Product_43",
                            Price = 89.7884228994036m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7167)
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7175),
                            Name = "CoffeeMakers_Product_44",
                            Price = 59.7676686838956m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7179)
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7187),
                            Name = "CoffeeMakers_Product_45",
                            Price = 94.6247976547816m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7190)
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7199),
                            Name = "CoffeeMakers_Product_46",
                            Price = 79.3922591720656m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7202)
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7211),
                            Name = "Grinders_Product_47",
                            Price = 11.125933462475m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7214)
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7223),
                            Name = "Grinders_Product_48",
                            Price = 93.1611463802165m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7226)
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7235),
                            Name = "Grinders_Product_49",
                            Price = 32.6823529970965m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7238)
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7246),
                            Name = "Grinders_Product_50",
                            Price = 31.6090340944141m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7250)
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7258),
                            Name = "Grinders_Product_51",
                            Price = 43.9368961326137m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7261)
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7269),
                            Name = "Grinders_Product_52",
                            Price = 33.1948625417296m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7273)
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7281),
                            Name = "Mugs_Product_53",
                            Price = 27.3090894594954m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7285)
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7293),
                            Name = "Mugs_Product_54",
                            Price = 94.2113881320084m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7297)
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7305),
                            Name = "Mugs_Product_55",
                            Price = 64.8626023032981m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7309)
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7317),
                            Name = "Mugs_Product_56",
                            Price = 93.0890766424439m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7320)
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7328),
                            Name = "Mugs_Product_57",
                            Price = 50.1925073325685m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7332)
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7340),
                            Name = "Mugs_Product_58",
                            Price = 31.8941411345948m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7344)
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7351),
                            Name = "Mugs_Product_59",
                            Price = 23.7518659771261m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7355)
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7364),
                            Name = "Filters_Product_60",
                            Price = 4.79475469428498m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7367)
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7375),
                            Name = "Filters_Product_61",
                            Price = 84.8611387171619m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7379)
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7387),
                            Name = "Filters_Product_62",
                            Price = 60.6382650272542m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7390)
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7399),
                            Name = "Filters_Product_63",
                            Price = 67.4073157648788m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7402)
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7410),
                            Name = "Filters_Product_64",
                            Price = 57.8442382254183m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7414)
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7421),
                            Name = "Filters_Product_65",
                            Price = 13.5862667955025m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7425)
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7436),
                            Name = "Filters_Product_66",
                            Price = 99.7117859173012m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7440)
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7448),
                            Name = "Filters_Product_67",
                            Price = 26.0184142653336m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7451)
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7460),
                            Name = "Filters_Product_68",
                            Price = 3.6832538571831m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7464)
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7472),
                            Name = "Filters_Product_69",
                            Price = 96.9116747914363m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7476)
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7484),
                            Name = "Pastries_Product_70",
                            Price = 45.3893953151105m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7488)
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7496),
                            Name = "Pastries_Product_71",
                            Price = 9.38858622736738m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7500)
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7507),
                            Name = "Pastries_Product_72",
                            Price = 32.9258549957175m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7511)
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7519),
                            Name = "Pastries_Product_73",
                            Price = 19.4866780654345m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7522)
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7530),
                            Name = "Pastries_Product_74",
                            Price = 1.70476620685823m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7533)
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7541),
                            Name = "Pastries_Product_75",
                            Price = 40.2650638766267m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7544)
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7553),
                            Name = "Snacks_Product_76",
                            Price = 73.4230387335389m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7556)
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7564),
                            Name = "Snacks_Product_77",
                            Price = 40.9589861230304m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7568)
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7576),
                            Name = "Snacks_Product_78",
                            Price = 34.2816199122908m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7579)
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7587),
                            Name = "Snacks_Product_79",
                            Price = 88.7010792459029m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7591)
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7599),
                            Name = "Snacks_Product_80",
                            Price = 26.4281691808729m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7602)
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7610),
                            Name = "Snacks_Product_81",
                            Price = 88.971088520811m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7614)
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7623),
                            Name = "Syrups_Product_82",
                            Price = 45.968058202647m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7626)
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7634),
                            Name = "Syrups_Product_83",
                            Price = 42.8769318191842m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7638)
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7690),
                            Name = "Syrups_Product_84",
                            Price = 7.77713452014083m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7694)
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7703),
                            Name = "Syrups_Product_85",
                            Price = 0.0132762090122474m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7707)
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7714),
                            Name = "Syrups_Product_86",
                            Price = 49.0439865094317m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7718)
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7726),
                            Name = "Syrups_Product_87",
                            Price = 1.49661703104601m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7729)
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7737),
                            Name = "Syrups_Product_88",
                            Price = 89.5492494566897m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7741)
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7749),
                            Name = "Syrups_Product_89",
                            Price = 77.7295231461012m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7753)
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7761),
                            Name = "MilkAlternatives_Product_90",
                            Price = 60.6160353986163m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7764)
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7773),
                            Name = "MilkAlternatives_Product_91",
                            Price = 88.8079728076507m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7776)
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7784),
                            Name = "MilkAlternatives_Product_92",
                            Price = 8.75318977763622m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7788)
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7796),
                            Name = "MilkAlternatives_Product_93",
                            Price = 64.8705342105622m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7800)
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7808),
                            Name = "MilkAlternatives_Product_94",
                            Price = 3.09442380119083m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7811)
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7819),
                            Name = "MilkAlternatives_Product_95",
                            Price = 82.6454214163608m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7823)
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7831),
                            Name = "MilkAlternatives_Product_96",
                            Price = 75.2482343496904m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7834)
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7842),
                            Name = "MilkAlternatives_Product_97",
                            Price = 4.00503533595246m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7846)
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7854),
                            Name = "MilkAlternatives_Product_98",
                            Price = 1.2209191250697m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7858)
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7866),
                            Name = "MilkAlternatives_Product_99",
                            Price = 82.550260628718m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7869)
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7878),
                            Name = "Merchandise_Product_100",
                            Price = 78.7215372265757m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7882)
                        },
                        new
                        {
                            Id = 101,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7890),
                            Name = "Merchandise_Product_101",
                            Price = 89.9504724509384m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7893)
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7901),
                            Name = "Merchandise_Product_102",
                            Price = 98.8268198353156m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7905)
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7913),
                            Name = "Merchandise_Product_103",
                            Price = 37.254289283409m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7917)
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7925),
                            Name = "Merchandise_Product_104",
                            Price = 39.8099004261286m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7928)
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7936),
                            Name = "Merchandise_Product_105",
                            Price = 60.5305385040899m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7940)
                        },
                        new
                        {
                            Id = 106,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7948),
                            Name = "Merchandise_Product_106",
                            Price = 94.1961781870686m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7952)
                        },
                        new
                        {
                            Id = 107,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7960),
                            Name = "Subscriptions_Product_107",
                            Price = 63.5957284723047m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7964)
                        },
                        new
                        {
                            Id = 108,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7972),
                            Name = "Subscriptions_Product_108",
                            Price = 65.906797081904m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7976)
                        },
                        new
                        {
                            Id = 109,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7984),
                            Name = "Subscriptions_Product_109",
                            Price = 32.642403838893m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7988)
                        },
                        new
                        {
                            Id = 110,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(7997),
                            Name = "Subscriptions_Product_110",
                            Price = 92.9914496791189m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(8000)
                        },
                        new
                        {
                            Id = 111,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(8008),
                            Name = "Subscriptions_Product_111",
                            Price = 46.0817995979737m,
                            UpdatedAt = new DateTime(2024, 7, 11, 14, 21, 33, 247, DateTimeKind.Local).AddTicks(8012)
                        });
                });

            modelBuilder.Entity("CoffeeShop.Products.Api.Models.Category", b =>
                {
                    b.HasOne("CoffeeShop.Products.Api.Models.Category", "ParentCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("CoffeeShop.Products.Api.Models.Product", b =>
                {
                    b.HasOne("CoffeeShop.Products.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoffeeShop.Products.Api.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
